services:
  _defaults:
    autowire: true
    public: true
    autoconfigure: true


  Markocupic\ContaoBundleCreatorBundle\Listener\ContaoHook\AddCustomRegexpListener:
    tags:
      - { name: contao.hook, hook: addCustomRegexp, method: cbcbRegexp, priority: 0 }
