services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true


    Markocupic\ContaoBundleCreatorBundle\ExtensionGenerator\ExtensionGenerator:
        arguments:
        - '@session'
        - '@Markocupic\ContaoBundleCreatorBundle\ExtensionGenerator\Utils\FileStorage'
        - '@Markocupic\ContaoBundleCreatorBundle\ExtensionGenerator\Utils\Tags'
        - '@Markocupic\ContaoBundleCreatorBundle\ExtensionGenerator\Message\Message'
        - '%kernel.project_dir%'
        public: true

    Markocupic\ContaoBundleCreatorBundle\ExtensionGenerator\Utils\FileStorage:
        arguments:
        - '%kernel.project_dir%'
        public: true

    Markocupic\ContaoBundleCreatorBundle\ExtensionGenerator\Utils\Tags: ~

    Markocupic\ContaoBundleCreatorBundle\ExtensionGenerator\Message\Message: ~
