
    # Contao frontend module <?= $toplevelnamespace ?>\<?= $sublevelnamespace ?>\Controller\FrontendModule\<?= $frontendmoduleclassname ?><?="\n" ?>
    <?= $toplevelnamespace ?>\<?= $sublevelnamespace ?>\Controller\FrontendModule\<?= $frontendmoduleclassname ?>:
        tags:
        - { name: contao.frontend_module, category: <?= $frontendmodulecategory ?>, template: <?= $frontendmoduletemplate ?>, type: <?= $frontendmoduletype ?> }
        - { name: container.service_subscriber }
        public: true
